### ISSUE TITLE
Add Slack notifications

### ISSUE THREAD

**Issue by ehashman** [RackSec/alertlogic-lib#8]
- [x] Add GitHub integration
- [x] Add Travis build integration

**Comment by irinarenteria** [comment]
For future reference:

When switching a repo from private to public, the travis-ci endpoint changes from `travis-ci.com` to `travis-ci.org`. The `travis encrypt` command will default to the `.com` endpoint, so an `--org` flag needs to be appended for the redirect to happen.

Here is the command that worked:
`travis encrypt "account:token#channel" --add notifications.slack.rooms --org`
